/**
 * Super Stack sound.
 *
 * Every sound here is generated by the browser itself — there are no audio files to
 * download, so this adds nothing to load time. Browsers block sound until the player
 * interacts with the page, so `primeAudio()` is called on the first button press.
 */

let ctx: AudioContext | null = null;
let master: GainNode | null = null;
let muted = false;

function context(): AudioContext | null {
  if (typeof window === "undefined") return null;
  if (ctx) return ctx;
  const Ctor = window.AudioContext ?? (window as unknown as { webkitAudioContext?: typeof AudioContext }).webkitAudioContext;
  if (!Ctor) return null;
  try {
    ctx = new Ctor();
    master = ctx.createGain();
    master.gain.value = 0.3;
    master.connect(ctx.destination);
  } catch {
    return null;
  }
  return ctx;
}

/** Call once from a click or key press so the browser allows sound. */
export function primeAudio() {
  const c = context();
  if (c && c.state === "suspended") void c.resume();
}

export function setMuted(next: boolean) {
  muted = next;
  if (master) master.gain.value = next ? 0 : 0.3;
}

export function isMuted() {
  return muted;
}

type ToneOptions = {
  freq: number;
  /** Slide to this frequency over the note's length. */
  to?: number;
  duration?: number;
  type?: OscillatorType;
  gain?: number;
  /** Seconds to wait before playing. */
  delay?: number;
};

function tone({ freq, to, duration = 0.12, type = "square", gain = 0.5, delay = 0 }: ToneOptions) {
  const c = context();
  if (!c || !master || muted) return;
  const start = c.currentTime + delay;
  const osc = c.createOscillator();
  const env = c.createGain();
  osc.type = type;
  osc.frequency.setValueAtTime(freq, start);
  if (to && to !== freq) osc.frequency.exponentialRampToValueAtTime(Math.max(1, to), start + duration);
  env.gain.setValueAtTime(0.0001, start);
  env.gain.exponentialRampToValueAtTime(gain, start + 0.012);
  env.gain.exponentialRampToValueAtTime(0.0001, start + duration);
  osc.connect(env);
  env.connect(master);
  osc.start(start);
  osc.stop(start + duration + 0.02);
}

function noise({ duration = 0.2, gain = 0.4, delay = 0 }) {
  const c = context();
  if (!c || !master || muted) return;
  const start = c.currentTime + delay;
  const frames = Math.floor(c.sampleRate * duration);
  const buffer = c.createBuffer(1, frames, c.sampleRate);
  const data = buffer.getChannelData(0);
  for (let i = 0; i < frames; i++) data[i] = (Math.random() * 2 - 1) * (1 - i / frames);
  const src = c.createBufferSource();
  const env = c.createGain();
  const filter = c.createBiquadFilter();
  filter.type = "lowpass";
  filter.frequency.value = 900;
  env.gain.setValueAtTime(gain, start);
  env.gain.exponentialRampToValueAtTime(0.0001, start + duration);
  src.buffer = buffer;
  src.connect(filter);
  filter.connect(env);
  env.connect(master);
  src.start(start);
}

/** Catching a topping: a light blip that rises with the combo. */
function catchTopping(combo: number) {
  const step = Math.min(12, combo);
  tone({ freq: 440 * Math.pow(1.06, step), duration: 0.09, type: "square", gain: 0.35 });
}

/** Catching a protein: fatter and lower, so the big catches sound big. */
function catchProtein(combo: number) {
  const step = Math.min(12, combo);
  tone({ freq: 220 * Math.pow(1.05, step), to: 330 * Math.pow(1.05, step), duration: 0.16, type: "sawtooth", gain: 0.32 });
  tone({ freq: 110 * Math.pow(1.05, step), duration: 0.14, type: "triangle", gain: 0.3 });
}

/** Reaching a new combo tier. */
function comboUp(multiplier: number) {
  const base = 520 + multiplier * 90;
  tone({ freq: base, duration: 0.07, type: "square", gain: 0.3 });
  tone({ freq: base * 1.5, duration: 0.09, type: "square", gain: 0.28, delay: 0.07 });
}

/** Catching a fumble object. */
function fumble() {
  tone({ freq: 200, to: 70, duration: 0.32, type: "sawtooth", gain: 0.4 });
  noise({ duration: 0.28, gain: 0.35 });
}

/** Letting good food hit the floor — quieter than a fumble, but you hear it. */
function drop() {
  tone({ freq: 240, to: 150, duration: 0.14, type: "triangle", gain: 0.22 });
}

/** Completing a Super Stack with the tiger-crunch lid. */
function superStack() {
  [523, 659, 784, 1047].forEach((freq, i) => {
    tone({ freq, duration: 0.16, type: "square", gain: 0.34, delay: i * 0.075 });
  });
  noise({ duration: 0.4, gain: 0.2, delay: 0.3 });
}

/** The last five seconds. */
function tick(urgent: boolean) {
  tone({ freq: urgent ? 900 : 660, duration: 0.07, type: "square", gain: 0.3 });
}

function roundOver() {
  [660, 550, 440, 330].forEach((freq, i) => {
    tone({ freq, duration: 0.2, type: "triangle", gain: 0.32, delay: i * 0.12 });
  });
}

function uiPress() {
  tone({ freq: 660, to: 880, duration: 0.09, type: "square", gain: 0.28 });
}

export const sfx = {
  catchTopping,
  catchProtein,
  comboUp,
  fumble,
  drop,
  superStack,
  tick,
  roundOver,
  uiPress,
};
