/**
 * Super Stack sound.
 *
 * Every sound is generated by the browser itself — no audio files, nothing to download.
 * Browsers block sound until the player interacts with the page, so `primeAudio()` is
 * called on the first button press. `setMuted()` is wired to the speaker button in the UI.
 *
 * The music is a tiny generative loop (kick, hat, two-note bass) whose tempo and energy
 * follow the phase of the round — it exists to give the cabinet a pulse, not to be a song.
 */

let ctx: AudioContext | null = null;
let master: GainNode | null = null;
let musicGain: GainNode | null = null;
let muted = false;

const MASTER_VOLUME = 0.3;
const MUSIC_VOLUME = 0.16;

function context(): AudioContext | null {
  if (typeof window === "undefined") return null;
  if (ctx) return ctx;
  const Ctor = window.AudioContext ?? (window as unknown as { webkitAudioContext?: typeof AudioContext }).webkitAudioContext;
  if (!Ctor) return null;
  try {
    ctx = new Ctor();
    master = ctx.createGain();
    master.gain.value = MASTER_VOLUME;
    master.connect(ctx.destination);
    musicGain = ctx.createGain();
    musicGain.gain.value = MUSIC_VOLUME;
    musicGain.connect(master);
  } catch {
    return null;
  }
  return ctx;
}

/* ── Recorded samples ────────────────────────────────────────────────────── */

/** The real bank sound — plays when the lid lands and the sandwich is stacked. */
let bankBuffer: AudioBuffer | null = null;
let bankLoadStarted = false;

function loadBankSample() {
  const c = context();
  if (!c || bankBuffer || bankLoadStarted) return;
  bankLoadStarted = true;
  fetch(`${import.meta.env.BASE_URL}assets/sfx/bank.mp3`)
    .then((response) => response.arrayBuffer())
    .then((data) => c.decodeAudioData(data))
    .then((buffer) => {
      bankBuffer = buffer;
    })
    .catch(() => {
      // Decode or fetch failed — the synth fallback in bank() covers it.
      bankLoadStarted = false;
    });
}

/** Call from a click or key press so the browser allows sound. */
export function primeAudio() {
  const c = context();
  if (c && c.state === "suspended") void c.resume();
  loadBankSample();
}

export function setMuted(next: boolean) {
  muted = next;
  if (master) master.gain.value = next ? 0 : MASTER_VOLUME;
}

export function isMuted() {
  return muted;
}

type ToneOptions = {
  freq: number;
  to?: number;
  duration?: number;
  type?: OscillatorType;
  gain?: number;
  delay?: number;
  /** Route through the music bus instead of the effects bus. */
  music?: boolean;
};

function tone({ freq, to, duration = 0.12, type = "square", gain = 0.5, delay = 0, music = false }: ToneOptions) {
  const c = context();
  if (!c || !master || muted) return;
  const start = c.currentTime + delay;
  const osc = c.createOscillator();
  const env = c.createGain();
  osc.type = type;
  osc.frequency.setValueAtTime(freq, start);
  if (to && to !== freq) osc.frequency.exponentialRampToValueAtTime(Math.max(1, to), start + duration);
  env.gain.setValueAtTime(0.0001, start);
  env.gain.exponentialRampToValueAtTime(gain, start + 0.012);
  env.gain.exponentialRampToValueAtTime(0.0001, start + duration);
  osc.connect(env);
  env.connect(music && musicGain ? musicGain : master);
  osc.start(start);
  osc.stop(start + duration + 0.02);
}

function noise({ duration = 0.2, gain = 0.4, delay = 0, cutoff = 900, music = false }) {
  const c = context();
  if (!c || !master || muted) return;
  const start = c.currentTime + delay;
  const frames = Math.floor(c.sampleRate * duration);
  const buffer = c.createBuffer(1, frames, c.sampleRate);
  const data = buffer.getChannelData(0);
  for (let i = 0; i < frames; i++) data[i] = (Math.random() * 2 - 1) * (1 - i / frames);
  const src = c.createBufferSource();
  const env = c.createGain();
  const filter = c.createBiquadFilter();
  filter.type = "lowpass";
  filter.frequency.value = cutoff;
  env.gain.setValueAtTime(gain, start);
  env.gain.exponentialRampToValueAtTime(0.0001, start + duration);
  src.buffer = buffer;
  src.connect(filter);
  filter.connect(env);
  env.connect(music && musicGain ? musicGain : master);
  src.start(start);
}

/* ── Effects ─────────────────────────────────────────────────────────────── */

function catchTopping(combo: number) {
  const step = Math.min(12, combo);
  tone({ freq: 440 * Math.pow(1.06, step), duration: 0.09, type: "square", gain: 0.35 });
}

function catchProtein(combo: number) {
  const step = Math.min(12, combo);
  tone({ freq: 220 * Math.pow(1.05, step), to: 330 * Math.pow(1.05, step), duration: 0.16, type: "sawtooth", gain: 0.32 });
  tone({ freq: 110 * Math.pow(1.05, step), duration: 0.14, type: "triangle", gain: 0.3 });
}

function comboUp(multiplier: number) {
  const base = 520 + multiplier * 90;
  tone({ freq: base, duration: 0.07, type: "square", gain: 0.3 });
  tone({ freq: base * 1.5, duration: 0.09, type: "square", gain: 0.28, delay: 0.07 });
}

function fumble() {
  tone({ freq: 200, to: 70, duration: 0.32, type: "sawtooth", gain: 0.4 });
  noise({ duration: 0.28, gain: 0.35 });
}

function drop() {
  tone({ freq: 240, to: 150, duration: 0.14, type: "triangle", gain: 0.22 });
}

/** Banking a Fat Stack — the biggest sound in the game. Plays the recorded SFX. */
function bank(layers: number) {
  const c = context();
  if (c && master && !muted && bankBuffer) {
    const src = c.createBufferSource();
    const env = c.createGain();
    src.buffer = bankBuffer;
    env.gain.value = 0.95;
    src.connect(env);
    env.connect(master);
    src.start();
    return;
  }
  // Fallback if the recording has not loaded (first seconds offline, decode failure).
  const notes = [523, 659, 784, 1047];
  notes.forEach((freq, i) => tone({ freq, duration: 0.15, type: "square", gain: 0.34, delay: i * 0.07 }));
  tone({ freq: 1568 + layers * 40, duration: 0.3, type: "triangle", gain: 0.28, delay: 0.28 });
  noise({ duration: 0.35, gain: 0.18, delay: 0.28, cutoff: 4000 });
}

/** The tower falling over. */
function collapse() {
  tone({ freq: 300, to: 50, duration: 0.55, type: "sawtooth", gain: 0.42 });
  noise({ duration: 0.5, gain: 0.4, cutoff: 600 });
  noise({ duration: 0.35, gain: 0.3, delay: 0.18, cutoff: 400 });
}

/** A lid has entered the field. */
function lidIncoming() {
  tone({ freq: 880, duration: 0.09, type: "square", gain: 0.3 });
  tone({ freq: 1174, duration: 0.12, type: "square", gain: 0.3, delay: 0.09 });
}

/** One second before the lid drops: a two-note horn from the truck. */
function lidHorn() {
  tone({ freq: 440, duration: 0.18, type: "sawtooth", gain: 0.18 });
  tone({ freq: 660, duration: 0.2, type: "sawtooth", gain: 0.18, delay: 0.18 });
}

function bankItWarning() {
  [660, 660, 880].forEach((freq, i) => tone({ freq, duration: 0.1, type: "square", gain: 0.32, delay: i * 0.12 }));
}

function phaseSlam() {
  tone({ freq: 130, to: 260, duration: 0.25, type: "sawtooth", gain: 0.4 });
  noise({ duration: 0.2, gain: 0.25, cutoff: 2000 });
}

function tick(urgent: boolean) {
  tone({ freq: urgent ? 900 : 660, duration: 0.07, type: "square", gain: 0.3 });
}

function countBeep(final: boolean) {
  tone({ freq: final ? 880 : 440, duration: final ? 0.35 : 0.12, type: "square", gain: 0.34 });
}

function roundOver() {
  [660, 550, 440, 330].forEach((freq, i) => tone({ freq, duration: 0.2, type: "triangle", gain: 0.32, delay: i * 0.12 }));
}

function fanfare() {
  [523, 659, 784, 1047, 1319].forEach((freq, i) => tone({ freq, duration: 0.22, type: "square", gain: 0.3, delay: i * 0.09 }));
}

function uiPress() {
  tone({ freq: 660, to: 880, duration: 0.09, type: "square", gain: 0.28 });
}

/* ── Music ───────────────────────────────────────────────────────────────── */

let musicTimer: number | null = null;
let musicStep = 0;
let musicBpm = 104;

/** The two-bar pattern: kick on the beat, hat off-beat, bass alternating root/fifth. */
function musicBar() {
  const eighth = 60 / musicBpm / 2;
  for (let i = 0; i < 8; i++) {
    const t = i * eighth;
    if (i % 2 === 0) tone({ freq: 90, to: 45, duration: 0.1, type: "sine", gain: 0.9, delay: t, music: true });
    else noise({ duration: 0.04, gain: 0.35, delay: t, cutoff: 6000, music: true });
    if (i === 0) tone({ freq: 65, duration: eighth * 1.6, type: "triangle", gain: 0.5, delay: t, music: true });
    if (i === 4) tone({ freq: 98, duration: eighth * 1.6, type: "triangle", gain: 0.5, delay: t, music: true });
  }
  return eighth * 8;
}

export function startMusic() {
  const c = context();
  if (!c || musicTimer !== null) return;
  const loop = () => {
    const barSeconds = musicBar();
    musicStep += 1;
    musicTimer = window.setTimeout(loop, barSeconds * 1000);
  };
  loop();
}

export function stopMusic() {
  if (musicTimer !== null) {
    clearTimeout(musicTimer);
    musicTimer = null;
  }
}

/** Music follows the round's phase: calm, driving, frantic. */
export function setMusicIntensity(phase: "WARM UP" | "STACK IT" | "RUSH!" | string) {
  musicBpm = phase === "RUSH!" ? 138 : phase === "STACK IT" ? 118 : 104;
}

export const sfx = {
  catchTopping,
  catchProtein,
  comboUp,
  fumble,
  drop,
  bank,
  collapse,
  lidIncoming,
  lidHorn,
  bankItWarning,
  phaseSlam,
  tick,
  countBeep,
  roundOver,
  fanfare,
  uiPress,
};
